feat(events)!: improved event bus system
ChameleonFramework/Chameleon pull request #140
Opened 2022-08-28 16:38 UTC by joshuasing

**Summary**
Replace existing event system with a faster event bus system.

**Changes**
 - Update README.md to use Sonatype repository.
 - Remove existing event system.
 - Add new event bus system.
 - Add event bus tests.

2022-08-28 16:53 UTC, SLLCoding submitted a review, later dismissed

2022-08-28 16:53 UTC, SLLCoding commented on api/src/main/java/dev/hypera/chameleon/events/common/UserConnectEvent.java
> +public final class UserConnectEvent implements UserEvent {
Should probably allow cancellation on this event.

2022-08-28 16:53 UTC, SLLCoding commented on api/src/main/java/dev/hypera/chameleon/events/proxy/ProxyUserSwitchEvent.java
> +public final class ProxyUserSwitchEvent implements ProxyUserEvent {
This event should also probably be cancellable.

2022-08-29 01:40 UTC, joshuasing commented on api/src/main/java/dev/hypera/chameleon/events/common/UserConnectEvent.java
> +public final class UserConnectEvent implements UserEvent {
This event is not cancellable on any platform.
To do this, we would need to implement kick-related events and kick the player when the event is cancelled.

2022-08-29 01:42 UTC, joshuasing commented on api/src/main/java/dev/hypera/chameleon/events/proxy/ProxyUserSwitchEvent.java
> +public final class ProxyUserSwitchEvent implements ProxyUserEvent {
This event is not cancellable on BungeeCord or Velocity unless we listen to the pre-switch events which could be too early for dispatching this event.

2022-08-29 06:50 UTC, SLLCoding commented on api/src/main/java/dev/hypera/chameleon/events/common/UserConnectEvent.java
> +public final class UserConnectEvent implements UserEvent {
I believe it'll be worth implementing that.

2022-08-29 06:51 UTC, joshuasing commented on api/src/main/java/dev/hypera/chameleon/events/common/UserConnectEvent.java
> +public final class UserConnectEvent implements UserEvent {
Should that be done in this pull request or a separate one?

2022-09-01 12:32 UTC, SLLCoding requested changes

2022-09-01 12:32 UTC, SLLCoding commented on platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/events/VelocityListener.java
>      }
This technically isn't a disconnect?

2022-09-01 12:32 UTC, SLLCoding commented on api/src/main/java/dev/hypera/chameleon/events/common/UserDisconnectEvent.java
> +    private final @Nullable Component reason;
This should probably be `@NotNull` with a default value.

2022-09-01 12:32 UTC, SLLCoding commented on api/src/main/java/dev/hypera/chameleon/events/common/UserDisconnectEvent.java
> +    }
If the field becomes `@NotNull`, then this should not be an `Optional`.

2022-09-01 14:11 UTC, SLLCoding approved these changes

2022-09-01 14:11 UTC, SLLCoding commented on platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/events/VelocityListener.java
> +            }
Should probably be put into a private method to make changes lightly easier. Just a nit-pick.

2022-09-01 14:25 UTC, SLLCoding submitted a review, later dismissed

2022-09-02 08:46 UTC, SLLCoding approved these changes

2022-09-02 08:50 UTC, merged