feat: add metadata, user caching, improve event dispatch
ChameleonFramework/Chameleon pull request #290
Opened 2023-09-20 16:53 UTC by joshuasing

**Summary**
Add user metadata system, add user caching, improve event dispatch, improve audience provider.

Fixes #216

**Changes**
- Add user metadata system (fix #216)
- Add user caching
- Improve event dispatch
- Improve audience provider

**Checklist**
- [x] I acknowledge and agree to the terms of the [Developer Certificate of Origin](https://developercertificate.org/).
- [x] All contributed code can be distributed under the terms of the [MIT License](https://github.com/ChameleonFramework/Chameleon/blob/main/LICENSE).
- [x] I have read the [contributing guidelines](https://github.com/ChameleonFramework/Chameleon/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/ChameleonFramework/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have checked the ["Allow edit from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) option.
- [x] I have added appropriate unit tests for my changes.

2023-10-02 21:05 UTC, LooFifteen requested changes
Looks like a load of listeners don't ever get unregistered, which could cause problems when people are using plugins like Plugman. We should be handling support for these kind of plugins because the end user of Chameleon does not have the option to.

2023-10-02 21:05 UTC, LooFifteen commented on platform-nukkit/src/main/java/dev/hypera/chameleon/platform/nukkit/event/NukkitEventDispatcher.java
> +public final class NukkitEventDispatcher extends PlatformEventDispatcher implements Listener {
Does this class unregister its listeners?

2023-10-02 21:05 UTC, LooFifteen commented on platform-sponge/src/main/java/dev/hypera/chameleon/platform/sponge/user/SpongeUserManager.java
> +        );
Are these unregistered either?

2023-10-03 07:03 UTC, joshuasing commented on platform-nukkit/src/main/java/dev/hypera/chameleon/platform/nukkit/event/NukkitEventDispatcher.java
> +public final class NukkitEventDispatcher extends PlatformEventDispatcher implements Listener {
Nukkit does not appear to provide a way to unregister listeners:
https://javadoc.io/doc/cn.powernukkitx/powernukkitx/latest/cn/nukkit/plugin/PluginManager.html
(PowerNukkitX javadoc, I cannot find NukkitX javadoc)

2023-10-03 07:30 UTC, joshuasing commented on platform-nukkit/src/main/java/dev/hypera/chameleon/platform/nukkit/event/NukkitEventDispatcher.java
> +public final class NukkitEventDispatcher extends PlatformEventDispatcher implements Listener {
Never mind, they have the exact same API as Bukkit: https://javadoc.io/doc/cn.powernukkitx/powernukkitx/latest/cn/nukkit/event/HandlerList.html

2023-10-03 15:30 UTC, merged