build: cleanup adventure serializer dependence
ChameleonFramework/Chameleon pull request #338
Opened 2023-11-27 07:46 UTC by joshuasing

**Summary**
Internally, Chameleon uses the legacy and GSON Adventure component
serializers. However, as they are not a part of the API nor are needed
by end-users, they should not be exposed as `api` dependencies.

Additionally, the legacy serializer is only required by the Bukkit and
Nukkit platform implementations, and should not be a dependency of the
API module.

**Changes**
- Remove dependence on legacy component serializer from API module
- Add dependence on legacy component serializer to Bukkit and Nukkit modules
- Make component serializer dependencies `implementation` to avoid exposing them to end-users.

**Checklist**
- [x] I acknowledge and agree to the terms of the [Developer Certificate of Origin](https://developercertificate.org/).
- [x] All contributed code can be distributed under the terms of the [MIT License](https://github.com/ChameleonFramework/Chameleon/blob/main/LICENSE).
- [x] I have read the [contributing guidelines](https://github.com/ChameleonFramework/Chameleon/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/ChameleonFramework/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have checked the ["Allow edit from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) option.
- [ ] I have added appropriate unit tests for my changes.

2023-11-27 07:54 UTC, LooFifteen requested changes
why is `implementation` used over `api`?

2023-11-27 08:02 UTC, joshuasing commented
> why is `implementation` used over `api`?

`implementation` does not expose the dependency to consumers, `api` does. [Gradle documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#:~:text=The%20api%20configuration%20should%20be,are%20internal%20to%20the%20component.):
>  The `api` configuration should be used to declare dependencies which are exported by the library API, whereas the `implementation` configuration should be used to declare dependencies which are internal to the component.

As the text serializers are not used in the API, and are only used internally, I don't think they should be `api` dependencies.

2023-11-27 17:43 UTC, LooFifteen commented
If the dependents do not know about these libraries, they will not be downloaded - causing them to not be compiled into the final jar, no?

2023-11-28 07:59 UTC, LooFifteen approved these changes

2023-11-28 07:59 UTC, merged