chore: Rewrite
ChameleonFramework/Chameleon pull request #62
Opened 2022-03-02 10:23 UTC by joshuasing

This pull request:
 - Rewrites most of Chameleon from scratch
 - Bumps version to 0.4.0-SNAPSHOT

Before this is merged, the following should be completed:
 - Merge [ChameleonFramework/Example#6](https://github.com/ChameleonFramework/Example/pull/6)

2022-03-02 17:31 UTC, SLLCoding requested changes
this took 1 and a half hours lmfao

2022-03-02 17:31 UTC, SLLCoding commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/listeners/VelocityListener.java
> +		if (event.getPreviousServer().isPresent() && event.getPlayer().getCurrentServer().isPresent()) {
hm?

2022-03-02 17:31 UTC, SLLCoding commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/user/VelocityUser.java
> +	}
Does this actually send the player to the server?

2022-03-02 17:31 UTC, SLLCoding commented on pom.xml
> +      <name>SLLCoding</name>
Should be `SLLCoding, Luis`

2022-03-03 02:32 UTC, joshuasing commented on .github/dependabot.yml
> -      interval: "daily"
I started setting up Renovate as it allows us to group dependency updates instead of constantly creating more pull requests.

2022-03-03 02:32 UTC, joshuasing commented on README.md
> +Chameleon is a framework created to aid in the creation of cross-platform Minecraft platforms.
Oops

2022-03-03 03:06 UTC, joshuasing commented on platform-spigot/src/main/java/dev/hypera/chameleon/platforms/spigot/managers/SpigotScheduler.java
> +		Bukkit.getScheduler().scheduleSyncRepeatingTask(chameleon.getSpigotPlugin(), () -> schedule(runnable), unit.toSeconds(delay) * 20, unit.toSeconds(period) * 20);
`BukkitScheduler#scheduleAsyncRepeatingTask` is deprecated, so instead I schedule a sync repeating task and run the task async when called. This is probably not the best way to do this but it works.

2022-03-03 03:06 UTC, joshuasing commented on platform-minestom/src/main/java/dev/hypera/chameleon/platforms/minestom/adventure/MinestomAudienceProvider.java
> +
I cannot find a method that allows me to close Adventure on Minestom.

2022-03-03 03:08 UTC, joshuasing commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/listeners/VelocityListener.java
> +		if (event.getPreviousServer().isPresent() && event.getPlayer().getCurrentServer().isPresent()) {
Velocity dispatches the `ServerConnectedEvent` when the player joins the proxy, this if statement makes the event more like BungeeCord's.

2022-03-03 03:09 UTC, joshuasing commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/platform/objects/VelocityPlugin.java
> +		return Paths.get("/");
I cannot find that method.

2022-03-03 03:15 UTC, joshuasing commented on platform-bungeecord/src/main/java/dev/hypera/chameleon/platforms/bungeecord/managers/BungeeCordPluginManager.java
> +		return Optional.ofNullable(ProxyServer.getInstance().getPluginManager().getPlugin(name)).map(BungeeCordPlugin::new);
`Optional.ofNullable(...)` returns empty if the provided value is null.

2022-03-03 07:50 UTC, SLLCoding commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/platform/objects/VelocityPlugin.java
> +		return Paths.get("/");
It's an interface inside the velocity package that all Velocity Chameleon instances should implement.

2022-03-03 07:52 UTC, SLLCoding approved these changes

2022-03-04 04:01 UTC, joshuasing commented on platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/platform/objects/VelocityPlugin.java
> +		return Paths.get("/");
I may have completely misunderstood this but, this class is used for wrapping platform plugins, not all platform plugins may be using chameleon so we cannot do that.

2022-03-04 04:09 UTC, joshuasing commented on platform-minestom/src/main/java/dev/hypera/chameleon/platforms/minestom/command/MinestomCommand.java
> +		});
Due to how Minestom works it appears as so I cannot easily implement tab completion.

2022-03-04 04:09 UTC, merged